package com.tablehub.thbackend.dto;

public enum MessageTypeEnum {
    QUERY_RESTAURANTS_REQUEST,
    QUERY_RESTAURANTS_RESPONSE,
    SUBSCRIBE_RESTAURANT_UPDATES_REQUEST,
    SUBSCRIBE_RESTAURANT_UPDATES_RESPONSE,
    UNSUBSCRIBE_RESTAURANT_UPDATES_REQUEST,
    TABLE_STATUS_CHANGED_EVENT,
    UPDATE_TABLE_STATUS_REQUEST,
    UPDATE_TABLE_STATUS_RESPONSE,
    ERROR_RESPONSE
}
